server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sion_test?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: mysql
logging.level:
  org.hibernate.SQL: debug

jwt:
  secret-key: simple_token.project_2024_09.secret_key
  # 1 day
  token.expired-time-ms: 86400000